version: '3.8'

services:
  amazon-deals:
    image: zduts/amazondeals:latest
    container_name: amazon-deals
    restart: unless-stopped
    ports:
      - "7777:8000"
    volumes:
      - ./data:/app/data
    environment:
      - FLARESOLVERR_URL=http://flaresolverr:8191 # IP of your Flaresolverr or container name if on same network
